URL_SCHEME = 'https://'

ALLOWED_METHODS = frozenset(['GET', 'POST', 'PUT', 'DELETE', 'PATCH'])
BODY_METHODS = frozenset(['POST', 'PUT', 'PATCH'])
QUERY_METHODS = frozenset(['GET', 'DELETE'])

DEFAULT_CONTENT_HEADERS = {'content-type': 'application/json'}

STATUS_OK = 200
STATUS_INVALID_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_CONFLICT = 409
STATUS_UNPROCESSABLE_ENTITY = 422
STATUS_INTERNAL_SERVER_ERROR = 500
STATUS_SERVICE_UNAVAILABLE = 503

VALID_TOKEN_TYPES = frozenset(['token'])
